### ISSUE TITLE
release build (-O3) fails: TypeError: (intermediate value) is not a function

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/NetCraft#58]
Broke with https://github.com/satoshinm/NetCraft/commit/89cabbe839866a0fab199588ab267917af0cb4ab

```
release-build-js $ rm craft*; make
[  5%] Linking C executable craft.html

/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272
        throw new JS_Parse_Error(message, line, col, pos);
        ^
TypeError: (intermediate value) is not a function
    at new JS_Parse_Error (/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:261:21)
    at js_error (/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:272:15)
    at croak (/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:742:17)
    at token_error (/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:749:17)
    at unexpected (/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:755:17)
    at Object.semicolon (/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:775:51)
    at prog1 (/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1314:29)
    at simple_statement (/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:906:35)
    at /Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:816:35
    at /Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/eliminator/node_modules/uglify-js/lib/parse-js.js:1297:32
Traceback (most recent call last):
  File "/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/emcc", line 13, in <module>
    emcc.run()
  File "/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/emcc.py", line 1976, in run
    JSOptimizer.flush()
  File "/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/emcc.py", line 1871, in flush
    run_passes(chunks[0], title, just_split=False, just_concat=False)
  File "/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/emcc.py", line 1844, in run_passes
    final = shared.Building.js_optimizer(final, passes, debug_level >= 4, JSOptimizer.extra_info, just_split=just_split, just_concat=just_concat)
  File "/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/shared.py", line 2046, in js_optimizer
    ret = js_optimizer.run(filename, passes, NODE_JS, debug, extra_info, just_split, just_concat)
  File "/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/js_optimizer.py", line 563, in run
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/js_optimizer.py", line 563, in <lambda>
    return temp_files.run_and_clean(lambda: run_on_js(filename, passes, js_engine, source_map, extra_info, just_split, just_concat))
  File "/Users/admin/games/wasm/emsdk-portable/emscripten/1.37.9/tools/js_optimizer.py", line 502, in run_on_js
    assert proc.returncode == 0
AssertionError
```

**Comment by satoshinm** [comment]
src/pre.js, this works:

```js
const args = unescape(document.location.hash).substring(1);
const argv = args === "" ? [] : args.split(' ');
Module['arguments'] = argv;
```

but this breaks, causing the above error during optimization:

```js
const args = unescape(document.location.hash).substring(1);
let argv = args === "" ? [] : args.split(' ');
Module['arguments'] = argv;
```

I also had similar parse errors with arrow functions before. This is ES6, apparently the uglifyjs in emscripten optimization is only ES5 capable?
